models/Customer.php
<?php

/**
 * This is the model class for table "customer".
 *
 * The followings are the available columns in table 'customer':
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $building
 * @property string $street
 * @property string $area
 * @property string $city
 * @property string $country
 * @property string $postcode
 */
class Customer extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'customer';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('first_name, last_name, building, street, area, city, country, postcode', 'required'),
			array('first_name, last_name, building, street, area, city, country', 'length', 'max'=>64),
			array('postcode', 'length', 'max'=>9),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, first_name, last_name, building, street, area, city, country, postcode', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'orders' => array(self::HAS_MANY, 'Order', 'order_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'first_name' => 'First Name',
			'last_name' => 'Last Name',
			'building' => 'Building',
			'street' => 'Street',
			'area' => 'Area',
			'city' => 'City',
			'country' => 'Country',
			'postcode' => 'Postcode',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('first_name',$this->first_name,true);
		$criteria->compare('last_name',$this->last_name,true);
		$criteria->compare('building',$this->building,true);
		$criteria->compare('street',$this->street,true);
		$criteria->compare('area',$this->area,true);
		$criteria->compare('city',$this->city,true);
		$criteria->compare('country',$this->country,true);
		$criteria->compare('postcode',$this->postcode,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Customer the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function getFullName() {
		return $this->first_name.' '.$this->last_name;
	}
	
	public function getFullAddress() {
		$address = '';
		$fields = array('building', 'street', 'area', 'city', 'country');
		
		foreach ($fields as $field) {
			if ($this->$field != '') {
				$address.= $this->$field.', ';
			} // if
		} // foreach
		
		$address.= $this->postcode;
		
		return $address;
	}
}

models/Order.php
<?php

/**
 * This is the model class for table "order".
 *
 * The followings are the available columns in table 'order':
 * @property integer $id
 * @property integer $customer_id
 * @property integer $product_id
 * @property double $product_price
 * @property integer $delivery_id
 * @property double $delivery_price
 * @property string $date_placed
 */
class Order extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'order';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('customer_id, product_id, product_price, delivery_id, delivery_price, date_placed', 'required'),
			array('customer_id, product_id, delivery_id', 'numerical', 'integerOnly'=>true),
			array('product_price, delivery_price', 'numerical'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, customer_id, product_id, product_price, delivery_id, delivery_price, date_placed', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
			'delivery' => array(self::BELONGS_TO, 'Delivery', 'delivery_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'customer_id' => 'Customer',
			'product_id' => 'Product',
			'product_price' => 'Product Price',
			'delivery_id' => 'Delivery',
			'delivery_price' => 'Delivery Price',
			'date_placed' => 'Date Placed',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('customer_id',$this->customer_id);
		$criteria->compare('product_id',$this->product_id);
		$criteria->compare('product_price',$this->product_price);
		$criteria->compare('delivery_id',$this->delivery_id);
		$criteria->compare('delivery_price',$this->delivery_price);
		$criteria->compare('date_placed',$this->date_placed,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Order the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function getTotal() {
		return number_format($this->product_price + $this->delivery_price, 2);
	}
}

controllers/OrderController.php
<?php

class OrderController extends McecomController {
	
	public function actionCreate() {
		$order = new Order;
		$customers = Customer::model()->findAll();
		$deliveries = Delivery::model()->findAll();
		$products = Product::model()->findAll();
		
		if ($this->isFormSubmitted() ) {
			$order->attributes = $this->request['Order'];
			$order->date_placed = date('Y-m-d H:i:s');
			
			if ($order->save() ) {
				Yii::app()->user->setFlash('success', 'Order Placed');
			
				$this->redirect($this->createUrl('home/index'));
			} else {
				Yii::app()->user->setFlash('error', 'There were errors with your form');
			} // if
		} // if
		
		$this->render('order-form', array(
			'model' => $order,
			'customers' => $customers,
			'deliveries' => $deliveries,
			'products' => $products,
		));
	} // function
		
	public function actionList() {
		$orders = Order::model()->with('customer')->findAll();
		
		$this->render('order-listing', array(
			'orders' => $orders,
		));
	} // function
	
	public function actionDetail($id) {
		$order = Order::model()->with(array(
			'customer',
			'product',
			'delivery',
		))->findByPk($id);
		
		if (!$order) {
			Yii::app()->user->setFlash('error', 'Could not find selected order information');
			
			$this->redirect($this->createUrl('order/list'));
		} // if
		
		$this->render('order-detail', array(
			'order' => $order,
		));
	} // function
	
} // class

views/order/order-detail.php
<table>
	<tr>
		<th>ID</th>
		<td><?php echo($order->id); ?></td>
	</tr>
	<tr>
		<th>Date</th>
		<td><?php echo date('d/m/y - H:i', strtotime($order->date_placed) ); ?></td>
	</tr>
	<tr>
		<th>Total</th>
		<td>&pound;<?php echo number_format($order->total, 2); ?></td>
	</tr>
	<tr>
		<th>Name</th>
		<td><?php echo($order->customer->fullName); ?></td>
	</tr>
	<tr>
		<th>Address</th>
		<td><?php echo($order->customer->fullAddress); ?></td>
	</tr>
	<tr>
		<th>Product ID</th>
		<td><?php echo($order->product_id); ?></td>
	</tr>
	<tr>
		<th>Product Name</th>
		<td><?php echo($order->product->name); ?></td>
	</tr>
	<tr>
		<th>Product Price</th>
		<td>&pound;<?php echo number_format($order->product_price, 2); ?></td>
	</tr>
	<tr>
		<th>Delivery ID</th>
		<td><?php echo($order->delivery_id); ?></td>
	</tr>
	<tr>
		<th>Delivery Name</th>
		<td><?php echo($order->delivery->name); ?></td>
	</tr>
	<tr>
		<th>Delivery Price</th>
		<td>&pound;<?php echo number_format($order->delivery_price, 2); ?></td>
	</tr>
</table>

<a href='<?php echo $this->createUrl('order/list'); ?>'>Back</a>

views/order/order-form.php
<? echo Yii::app()->controller->module->registerCss('main.css'); ?>
<?php
	foreach(Yii::app()->user->getFlashes() as $key => $message) {
		echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
	} // foreach
?>
<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'order-form',
	'focus' => array($model, 'customer_id'),
)); ?>

<?php echo $form->errorSummary($model); ?>

<div class='row'>
	<div class='input-wrap'>
		<?php echo $form->labelEx($model, 'customer_id'); ?>
		<?php echo $form->dropDownList($model, 'customer_id', CHtml::listData($customers, 'id', 'fullName'), array('empty' => 'Select Customer')); ?>
		<?php echo $form->error($model, 'customer_id'); ?>
	</div>
</div>

<div class='row'>
	<div class='input-wrap'>
		<?php echo $form->labelEx($model, 'product_id'); ?>
		<?php echo $form->dropDownList(
			$model, 
			'product_id', 
			CHtml::listData($products, 'id', 'name'), 
			array(
				'empty' => 'Select Product',
				'ajax' => array(
					'type' => 'POST',
					'url' => $this->createUrl('ajax/getProductPrice'),
					'update' => '#Order_product_price',
				),
			)
		); ?>
		<?php echo $form->error($model, 'product_id'); ?>
	</div>
	<div class='input-wrap'>
		<?php echo $form->labelEx($model, 'product_price'); ?>
		<span class='prefix'>&pound;</span><?php echo $form->textField($model, 'product_price'); ?>
		<?php echo $form->error($model, 'product_price'); ?>
	</div>
</div>

<div class='row'>
	<div class='input-wrap'>
		<?php echo $form->labelEx($model, 'delivery_id'); ?>
		<?php echo $form->dropDownList(
			$model, 
			'delivery_id', 
			CHtml::listData($deliveries, 'id', 'name'), 
			array(
				'empty' => 'Select Delivery',
				'ajax' => array(
					'type' => 'POST',
					'url' => $this->createUrl('ajax/getDeliveryPrice'),
					'update' => '#Order_delivery_price',
				),
			)
		); ?>
		<?php echo $form->error($model, 'delivery_id'); ?>
	</div>
	<div class='input-wrap'>
		<?php echo $form->labelEx($model, 'delivery_price'); ?>
		<span class='prefix'>&pound;</span><?php echo $form->textField($model, 'delivery_price'); ?>
		<?php echo $form->error($model, 'delivery_price'); ?>
	</div>
</div>

<div class='row'>
	<?php echo CHtml::submitButton('Place Order', array('class' => 'button') ); ?>
	<a class='button' href='<?php echo $this->createUrl('home/index'); ?>'>Back</a>
</div>

<?php $this->endWidget(); ?>

views/order/order-listing.php
<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Date</th>
			<th>Name</th>
			<th>Address</th>
			<th>Total</th>
			<th>&nbsp</th>
		</tr>
	</thead>
	<tbody>
		<?php if (count($orders) <= 0) { ?>
			<tr>
				<td colspan='6'>No orders placed yet</td>
			</tr>
		<?php } else { ?>
			<?php foreach ($orders as $order) { ?>
				<tr>
					<td><?php echo $order->id; ?></td>
					<td><?php echo date('d/m/y - H:i', strtotime($order->date_placed) ); ?></td>
					<td><?php echo $order->customer->fullName; ?></td>
					<td><?php echo $order->customer->fullAddress; ?></td>
					<td>&pound;<?php echo $order->total; ?></td>
					<td><a href='<?php echo $this->createUrl('order/detail', array('id'=>$order->id) );?>'>View Details</a></td>
				</tr>
			<?php } // foreach ?>
		<?php } // if ?>
	</tbody>
</table>

<a href='<?php echo $this->createUrl('home/index'); ?>'>Back</a>