controllers/HomeController.php
<?php

class HomeController extends McecomController {
	
	public function actionIndex() {
		$this->pageTitle = Yii::app()->name.' - Menu';
		$this->render('index');
	} // function
	
} // class

controllers/OrderController.php
<?php

class OrderController extends McecomController {
	
	public function actionCreate() {
		$order = new Order;
		$customers = Customer::model()->findAll();
		$deliveries = Delivery::model()->findAll();
		$products = Product::model()->findAll();
		
		if ($this->isFormSubmitted() ) {
			$order->attributes = $this->request['Order'];
			$order->date_placed = date('Y-m-d H:i:s');
			
			if ($order->save() ) {
				Yii::app()->user->setFlash('success', 'Order Placed');
			
				$this->redirect($this->createUrl('home/index'));
			} else {
				Yii::app()->user->setFlash('error', 'There were errors with your form');
			} // if
		} // if
		
		$this->render('order-form', array(
			'model' => $order,
			'customers' => $customers,
			'deliveries' => $deliveries,
			'products' => $products,
		));
	} // function
		
	public function actionList() {
		$orders = Order::model()->with('customer')->findAll();
		
		$this->render('order-listing', array(
			'orders' => $orders,
		));
	} // function
	
	public function actionDetail($id) {
		$order = Order::model()->with(array(
			'customer',
			'product',
			'delivery',
		))->findByPk($id);
		
		if (!$order) {
			Yii::app()->user->setFlash('error', 'Could not find selected order information');
			
			$this->redirect($this->createUrl('order/list'));
		} // if
		
		$this->render('order-detail', array(
			'order' => $order,
		));
	} // function
	
} // class

views/home/index.php
<?php echo Yii::app()->controller->module->registerCss('main.css'); ?>
<?php
	foreach(Yii::app()->user->getFlashes() as $key => $message) {
		echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
	} // foreach
?>
<p>Choose an action below</p>
<div class='menu-tiles'>
	<div class='menu-tile'>
		<a href='<?php echo $this->createUrl('order/create');?>'>New Order</a>
	</div>
	<div class='menu-tile'>
		<a href='<?php echo $this->createUrl('order/list');?>'>View All Orders</a>
	</div>
</div>